### ISSUE TITLE
Istanbul test coverage is broken in es6 branch

### ISSUE THREAD

**Issue by thefourtheye** [pvenkatakrishnan/fastPath#5]
When I do `npm run cover`, I get this

    index.js -> dist/index.js
    lib/fastPath.js -> dist/lib/fastPath.js
    Transformation error; return original code
    { [Error: Line 1: Unexpected reserved word]
      index: 15,
      lineNumber: 1,
      column: 16,
      description: 'Unexpected reserved word' }
    Transformation error; return original code
    { [Error: Line 182: Unexpected token {]
      index: 4473,
      lineNumber: 182,
      column: 20,
      description: 'Unexpected token {' }
    TAP version 13
    # bookstore
    # should be able to parse simple object refs
    ok 1 should be equivalent
    # should be able to parse simple object refs
    ok 2 should be equivalent
    # should be able to parse simple object refs
    ok 3 should be equivalent
    ....
    ....
    ....
    ....
    ok 47 should be equivalent
    # should test named patterns
    ok 48 should be equivalent
    No coverage information was collected, exit without writing coverage information

    1..48
    # tests 48
    # pass  48

    # ok

**Comment by pvenkatakrishnan** [comment]
This was fixed.
