### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pipobscure** [pvenkatakrishnan/fastPath#8]
Hi all,

I would really like to use this at work, since it would make life a lot easier. However the fact that you have not included any licensing information in the repo or the readme, prevents me from doing this.

Could you please add an explicit license. Once you have that, I can get approval for the software and you can expect me to also start contributing.

Thanks!

**Comment by pvenkatakrishnan** [comment]
for sure i will do that today.

**Comment by pvenkatakrishnan** [comment]
Added an MIT license. Thank you for calling it out.
